services:
  MySQL:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tpfinal22
    healthcheck:
      # This requires mysqladmin installed on local machine
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-P", "3306"]
      interval: 3s
      timeout: 20s
      retries: 5
